const ADULT_KEYWORD_LIST = [
    "porn",
    "orgasm",
    "gangbang",
    "xnxx",
    "fuck",
    "hardfuck",
    "blowjob",
    "handjob",
    "jerkoff",
    "milf fuck",
    "milf video",
    "milf hd",
    "milf tube",
    "milf xxx",
    "nudesex",
    "nudevideo",
    "nudefuck",
    "nudetube",
    "nudescene",
    "nudehdvideo",
    "nudegirls",
    "nudebabe",
    "nudemodel",
    "cleavage",
    "drtuber",
    "spankwire",
    "keezmovie",
    "mofosex",
    "tubsexer",
    "befuck",
    "hdmovz",
    "slutload",
    "handjobhub",
    "tubevsex",
    "dansmovie",
    "fapdu",
    "camhubcc",
    "freudbox",
    "madthumbs",
    "eroxia",
    "deviantclip",
    "xxvids",
    "apetube",
    "elephanttube",
    "gangbang",
    "creampie",
    "masturbate",
    "seductive",
    "cuckold",
    "bukkake",
    "gagging",
    "cumshot",
    "threesome",
    "squirt",
    "busty",
    "deepthroat",
    "femdom",
    "femdom",
    "kinky",
    "scissoring",
    "sexscandal",
    "livejasmin",
    "nhentai",
    "indiansexstories",
    "luststories",
    "bdsmlibrary",
    "renderotica",
    "eroticillusions",
    "hentairules",
    "clubsissy",
    "jabcomix",
    "hentaihere",
    "smutjunkies",
    "lustomic",
    "xhamster",
    "redtube",
    "spankbang",
    "letmejerk",
    "hitomila",
    "myfreecams",
    "perfectgirls",
    "stripchat",
    "sexvid",
    "lanarhoades",
    "rileyreid",
    "abelladanger",
    "jordielninopolla",
    "maitlandward",
    "miamalkova",
    "adrianachechik",
    "jessicajaymes",
    "nicoleaniston",
    "brandilove",
    "leolulu",
    "lelastar",
    "angelawhite",
    "alexistexas",
    "lenapaul",
    "avaaddams",
    "lisaann",
    "kimmygranger",
    "dillionharper",
    "kendralust",
    "elsajean",
    "danidaniels",
    "xevbellringer",
    "sarajay",
    "sarahbanks",
    "alexisfawx",
    "lenatheplug",
    "asaakira",
    "madisonivy",
    "jessarhodes",
    "cheriedeville",
    "evalovia",
    "toriblack",
    "victoriacakes",
    "bridgetteb",
    "karmarx",
    "valentinanappi",
    "emilywillis",
    "petajensen",
    "sashagrey",
    "janicegriffith",
    "danikamori",
    "leahgotti",
    "augustames",
    "nicoletteshea",
    "owengray",
    "corychase",
    "abbeybrooks",
    "johnnysins",
    "roccosiffredi",
    "alexadams",
    "jamesdeen",
    "antoniomallorca",
    "dannyd",
    "tylernixon",
    "indiangay",
    "lesbiantube",
    "sunnyleone",
    "bellesaco",
    "trannyone",
    "kompozme",
    "gaymanflicks",
    "hairypussy",
    "pussylicked",
    "adultvideo",
    "nakedmom",
    "nakedgirl",
    "sexmovies",
    'الاباحية',
    'اللسان',
    'وظيفةضربة',
    'وظيفةاليد',
    'دسار',
    'رعشةقبالة',
    'جاكقبالة',
    'جبهةمورو',
    'الثدي',
    'عارية',
    'وظيفةاليد',
    'الثدي',
    'الانقسام',
    'فيديوالجنس',
    'بيكيني',
    'المثيرة',
    'الفتياتالساخنة',
    'مفلس',
    'شريطجنسي',
    'فضيحةجنسية',
    'অশ্লীল',
    'ব্লজব',
    'ব্লকজব',
    'হ্যান্ডজব',
    'ডিলডো',
    'জার্কঅফ',
    'জ্যাকঅফ',
    'সুন্দরিসেক্সিমহিলার',
    'বুবস',
    'নগ্ন',
    'হাতেরকাজ',
    'ক্লিভেজ',
    'সেক্সভিডিও',
    'বিকিনি',
    'যৌনউত্তেজক',
    'হটমেয়েরা',
    'স্কার্ট',
    'পীনস্তনী',
    'সেক্সটেপ',
    'সেক্সকেলেঙ্কারী',
    'kouření',
    'vyfukování',
    'ručnípráce',
    'trhnutí',
    'zvednutí',
    'honění',
    'štěpení',
    'sexvideo',
    'bikiny',
    'erotické',
    'horkédívky',
    'stříkání',
    'prsatá',
    'sexuálnípáska',
    'sexuálnískandál',
    'pupper',
    'kløvning',
    'erotisk',
    'wichsen',
    'wichsen',
    'brüste',
    'nackt',
    'titten',
    'spaltung',
    'erotik',
    'heissegirls',
    'sexskandal',
    'πορνό',
    'χτύπημα',
    'δουλειάχτυπήματος',
    'δουλειάμετοχέρι',
    'γυμνό',
    'μπικίνι',
    'ερωτικό',
    'καυτάκορίτσια',
    'mamada',
    'trabajomanual',
    'consolador',
    'masturbarse',
    'tetas',
    'desnudo',
    'paja sex',
    'paja video',
    'paja xxx',
    'paja hd',
    'tube de paja',
    'paja follar',
    'tetas',
    'escote',
    'videosexual',
    'erótico',
    'chicascalientes',
    'chorro',
    'tetona',
    'cintadesexo',
    'escándalosexual',
    'dibujos animados de adultos',
    'juego erotico',
    'espectáculos de dulces',
    'juguete sexual',
    'coño peludo',
    'coño afeitado',
    'pies fetiches',
    'película para adultos',
    'adulto',
    'sexo indio',
    'clips de sexo',
    'mamada',
    'golpea un',
    'masturbar',
    'milf sexo',
    'mierda milf',
    'video milf',
    'milf hd',
    'tubo milf',
    'milf xxx',
    'sexo desnudo',
    'video desnudo',
    'erótico',
    'chica caliente',
    'bomba de bomba',
    'tres unos pocos',
    'cinta de sexo',
    'garganta profunda',
    'garganta profunda',
    'escándalo sexo',
    'finder de amigos para adultos',
    'películas de sexo',
    'tetas de video',
    'tetas sexuales',
    'tetas tubos',
    'tetas chupan',
    'pechos grandes',
    'juguete adulto',
    'mamada amateur',
    'sexo aficionado',
    'follar anal',
    'mirar boquiabierto',
    'penetración anal',
    'sexo anal',
    'juguetes anal',
    'crema anal',
    'ataque de culo',
    'culo de crujido',
    'joder joder',
    'culo lamiendo',
    'babaca',
    'sofá de fundición',
    'lamiendo la bola',
    'chicas traviesas',
    'gran culo negro',
    'polla grande',
    'culo negro',
    'polla negra',
    'coño negro',
    'chicas regordetas',
    'frotar clítoris',
    'clítoris chupando',
    'chupar la polla',
    'niña sofá',
    'mujeres de puma',
    'cum en la boca',
    'cum en el coño',
    'cum en la mamas',
    'videos sexuales chica curvy',
    'montando un pene',
    'dick chupando',
    'anal doble',
    'doble penetración',
    'blusa de plumón',
    'comiendo coño',
    'videos sexuales exóticos',
    'follando la cara',
    'videos de sexo femenino',
    'orgasmo femenino',
    'digitación',
    'primer anal',
    'sexo por primera vez',
    'videos de sexo de red',
    'sexo a cuatro',
    'anal francés',
    'maldita sea hd',
    'maquinas sexuales',
    'pendejos bien abiertos',
    'sexo gay',
    'chica se la follan',
    'chica en la niña',
    'chica sexual',
    'dando cabeza',
    'sexo en grupo',
    'sexo en el gimnasio',
    'camara escondida',
    'videos de sexo casero',
    'culo enorme',
    'enorme polla negra',
    'videos de sexo esposa esposa',
    'videos de hypno sex',
    'videos de sexo incesto',
    'indio follada',
    'inserción de polla',
    'consolador de inserción',
    'videos de sexo interracial sexual',
    'sexo sin censura japonés',
    'sexo en vivo',
    'hombre contra hombre',
    'polla monstruo',
    'sexo oral',
    'videos orgía',
    'videos de sexo de pov',
    'vaquera inversa',
    'posiciones sexuales',
    'پورنو',
    'کارضربه',
    'کاربادست',
    'دیلدو',
    'حرکتتندوسریع',
    'جکخاموش',
    'مشاعره',
    'برهنه',
    'دستی',
    'جوانان',
    'شکاف',
    'فیلمسکس',
    'بیکینی',
    'شهوانی',
    'دخترانداغ',
    'سرنگ',
    'شلوغ',
    'نوارجنسی',
    'رسواییجنسی',
    'suihin',
    'isottyöt',
    'käsityöt',
    'tissit',
    'alaston',
    'pilkkominen',
    'seksivideo',
    'bikinit',
    'eroottinen',
    'kuumattytöt',
    'suihkuta',
    'seksiteippi',
    'seksiskandaali',
    'hubad',
    'erotik',
    'branler',
    'seins',
    'branlette',
    'clivage',
    'érotique',
    'filleschaudes',
    'plantureuse',
    'scandalesexuel',
    'पोर्न',
    'ब्लोजॉब',
    'हैंडजॉब',
    'डिल्डो',
    'झटकाबंद',
    'जैकऑफ',
    'एमआईएलटी',
    'स्तन',
    'नग्न',
    'हैंडजॉब',
    'स्तन',
    'दरार',
    'सेक्सवीडियो',
    'बिकनी',
    'कामुक',
    'हॉटगर्ल्स',
    'स्क्वर्ट',
    'बस्टी',
    'सेक्सटेप',
    'सेक्सस्कैंडल',
    'szopás',
    'hímvesszőmunka',
    'kézimunka',
    'vibrátor',
    'kivered',
    'jackki',
    'mellek',
    'meztelen',
    'kézimunka',
    'hasítás',
    'szexvideó',
    'erotikus',
    'forrólányok',
    'spriccel',
    'szexszalag',
    'szexbotrány',
    'pekerjaantangan',
    'brengsek',
    'payudara',
    'payudara',
    'belahandada',
    'videoseks',
    'erotis',
    'gadispanas',
    'muncrat',
    'berdada',
    'rekamanseks',
    'skandalseks',
    'pompino',
    'lavoromanuale',
    'scollatura',
    'erotico',
    'ragazzecalde',
    'schizzi',
    'procace',
    'scandalosessuale',
    'פורנו',
    'מציצה',
    'מכהעבודה',
    'עבודתיד',
    'דילדו',
    'אידיוט',
    'מילף',
    'ציצים',
    'עירום',
    'עבודתיד',
    'ציצים',
    'מחשוף',
    'סרטוןסקס',
    'ביקיני',
    'ארוטי',
    'בנותחמות',
    'להשפריץ',
    'חזהגדול',
    'קלטתסקס',
    'שערורייתמין',
    'エロアニメ',
    'ふたなり',
    '大人のための漫画',
    'アニメポルノ',
    'エロゲ',
    'エロゲーム',
    'セックスビデオ',
    'エロチック',
    'ホットガールズ',
    'セックステープ',
    'セックススキャンダル',
    '섹스비디오',
    '뜨거운여자',
    '섹스테이프',
    '섹스스캔들',
    'karêkarê',
    'karêdest',
    'girlshot',
    'tapesex',
    'skandalsex',
    'rankinisdarbas',
    'atsigręžti',
    'pakeltinuostalo',
    'nuogas',
    'rankųdarbo',
    'papai',
    'skilimas',
    'seksovaizdoįrašas',
    'erotika',
    'karštosmerginos',
    'pritūpimas',
    'seksojuosta',
    'seksoskandalas',
    'pekerjaantamparan',
    'pekerjaantangan',
    'bogel',
    'seks',
    'erotik',
    'gadispanas',
    'muncrat',
    'pitaseks',
    'skandalseks',
    'pupper',
    'klyving',
    'erotisk',
    'pijpbeurt',
    'aftrekken',
    'milfvideo',
    'milfsex',
    'milftube',
    'milfxxx',
    'milfhd',
    'milfneuken',
    'borsten',
    'naakt',
    'tieten',
    'decollete',
    'seksvideo',
    'erotisch',
    'hetemeiden',
    'spuiten',
    'rondborstig',
    'sekstape',
    'seksschandaal',
    'pupper',
    'klyving',
    'erotisk',
    'pupper',
    'klyving',
    'erotisk',
    'pracaręczna',
    'szarpaniesię',
    'mamuśki',
    'cycki',
    'nagie',
    'ręcznarobota',
    'cycki',
    'dekolt',
    'bikini',
    'erotyczne',
    'gorącedziewczyny',
    'tryskać',
    'skandalseksualny',
    'boquete',
    'punheta',
    'masturbar',
    'punheta',
    'vídeomilf',
    'sexomilf',
    'milftube',
    'milfxxx',
    'milfhd',
    'fodamilf',
    'nudez',
    'punheta',
    'tetas',
    'clivagem',
    'vídeodesexo',
    'biquíni',
    'erótico',
    'garotasgostosas',
    'esguicho',
    'peituda',
    'fitadesexo',
    'escândalosexual',
    'desenhos animados para adultos',
    'jogo erótico',
    'doces mostra',
    'brinquedo de sexo',
    'buceta peluda',
    'buceta raspada',
    'fetiche por pés filme adulto',
    'vid adulto',
    'sexo indiano',
    'clipes de sexo',
    'boquete',
    'bate uma',
    'jack off',
    'sexo milf',
    'milf foda',
    'vídeo milf',
    'milf hd',
    'tubo milf',
    'milf xxx',
    'sexo nu',
    'vídeo nu',
    'foda nua',
    'tubo nu',
    'cena nua',
    'hdvideo nua',
    'meninas nuas',
    'babe nua',
    'modelo nu',
    'trabalho de mão',
    'três alguns',
    'fita de sexo',
    'garganta profunda',
    'garganta profunda',
    'escândalo sexual',
    'filmes de sexo',
    'tits sexo',
    'tubos de tits',
    'tits chupar',
    'grandes mamas',
    'brinquedo adulto',
    'boquete amador',
    'sexo amador',
    'foda anal',
    'gape anal',
    'penetração anal',
    'sexo anal',
    'brinquedos anal',
    'creampie anal',
    'ataque de bunda',
    'crack ass',
    'foda-se burro',
    'bunda lambendo',
    'babaca de babaca',
    'teste do sofá',
    'ball lambendo',
    'garotas mal legais',
    ' bbw',
    'bunda preta grande',
    'pau grande',
    'bunda preta',
    'pau preto',
    'buceta negra',
    'garotas gordinhas',
    'clitóris rub',
    'clitóris chupando',
    'andar de pau',
    'chupar pau',
    'menina do sofá',
    'mulheres de cougar',
    'cum na boca',
    'cum na buceta',
    'cum em mamas',
    'vídeos de sexo menina curvy',
    'montando um pênis',
    'dick chupando',
    'anal duplo',
    'penetração dupla',
    'para baixo blusa',
    'comendo buceta',
    'vídeos sexuais exóticos',
    'fodendo a cara',
    'vídeos de sexo femininos',
    'orgasmo feminino',
    'dedilhado',
    'primeiro anal',
    'sexo pela primeira vez',
    'vídeos de sexo fishnet',
    'sexo a quatro',
    'anal francês',
    'porra hd',
    'fodendo máquinas',
    'babaca escancarado',
    'sexo gay',
    'garota fica fodida',
    'menina na menina',
    'sexo menina',
    'dando cabeça',
    'porra do grupo',
    'sexo grupal',
    'sexo de ginástica',
    'sexo duro duro',
    'câmera escondida',
    'vídeos de sexo caseiro',
    'enorme ass',
    'pau preto enorme',
    'marido esposa vídeos de sexo',
    'vídeos de sexo hipno',
    'vídeos sexuais de incesto',
    'indiano fodido',
    'inserção dick',
    'inserção dildo',
    'vídeos de sexo sexual interracial',
    'sexo sem censura japonês',
    'sexo ao vivo',
    'homem no homem',
    'pau monstro',
    'sexo oral',
    'vídeos orgia',
    'vídeos de sexo pov',
    'cowgirl reverso',
    'posições sexuais',
    'порно',
    'порево',
    'порнуха',
    'порнушка',
    'Русское порево',
    'минет',
    'минет',
    'рукаработа',
    'фаллоимитатор',
    'дрочить',
    'дрочить',
    'мамаша',
    'сиськи',
    'обнаженные',
    'мастурбирует',
    'титьки',
    'расщепление',
    'сексвидео',
    'бикини',
    'эротика',
    'горячиедевушки',
    'сквирт',
    'грудастая',
    'секслента',
    'сексскандал',
    'fajčenie',
    'vyhodiťprácu',
    'ručnézamestnanie',
    'trhnúť',
    'vyraziť',
    'prsia',
    'nahévideo',
    'nahýsex',
    'nahátrubka',
    'nahédívky',
    'naháxxx',
    'nahébabes',
    'nahásouložit',
    'naháňanie',
    'prsia',
    'štiepenie',
    'bikiny',
    'erotické',
    'striekanie',
    'sexskandál',
    'blowslužbo',
    'delozrokami',
    'kretenoff',
    'joške',
    'joške',
    'dekolte',
    'seksvideo',
    'erotično',
    'vročadekleta',
    'špricati',
    'sextrak',
    'seksškandal',
    'porrfilm',
    'porrsex',
    'porrxxx',
    'porrflickor',
    'porrknulla',
    'porrrör',
    'porrbabe',
    'bröst',
    'naken',
    'bröst',
    'klyvning',
    'erotisk',
    'hetaflickor',
    'spruta',
    'sexband',
    'sexskandal',
    'หัวนม',
    'ความแตกแยก',
    'วิดีโอเอ็กซ์',
    'บิกินี่',
    'สาวร้อน',
    'เซ็กซ์เทป',
    'เซ็กซ์อื้อฉาว',
    'oralseks',
    'elişi',
    'yapaypenis',
    'mastürbasyon',
    'kriko',
    'göğüsler',
    'çiplak',
    'memeler',
    'bölünme',
    'seksvideosu',
    'erotik',
    'ateşlikizlar',
    'fişkirtma',
    'sekskaseti',
    'seksskandali',
    'دھچکاکام',
    'دھچکاکام',
    'ہاتھکینوکری',
    'دلڈو',
    'جرکآف',
    'جیکآف',
    'شہوتانگیز',
    'چھاتی',
    'عریاں',
    'ہینڈکام',
    'چھاتی',
    'کلیویج',
    'سیکسویڈیو',
    'بیکنی',
    'شہوانی',
    'شہوتانگیز',
    'گرملڑکیاں',
    'اسکرٹ',
    'جنسیٹیپ',
    'جنسیاسکینڈل',
    'khiêudâm',
    'côngviệcthổi',
    'côngviệcthổi',
    'côngviệctay',
    'dươngvậtgiả',
    'giật',
    'phụnữ',
    'bikini',
    'khiêudâm',
    'băngsex',
    'scandaltìnhdục',
    '手工作业',
    '假阳具',
    '摩洛伊斯兰解放阵线',
    '性爱视频',
    '比基尼',
    '辣妹',
    '性爱录像带',
    '性丑闻'
]

const ADULT_WEBSITE_LIST = [
    "xvideos.com",
    "xhamster.com",
    "pornhub.com",
    "xnxx.com",
    "redtube.com",
    "youporn.com",
    "daftsex.com",
    "xxxvideos.com",
    "chaturbate.com",
    "xvideos2.com",
    "hqporner.com",
    "xhamster18.desi",
    "tube8.com",
    "youjizz.com",
    "hardsextube.com",
    "beeg.com",
    "motherless.com",
    "drtuber.com",
    "nuvid.com",
    "pornerbros.com",
    "spankwire.com",
    "keezmovies.com",
    "sunporno.com",
    "porn.com",
    "4tube.com",
    "alphaporno.com",
    "xtube.com",
    "pornoxo.com",
    "yobt.com",
    "tnaflix.com",
    "pornsharia.com",
    "brazzers.com",
    "extremetube.com",
    "slutload.com",
    "fapdu.com",
    "empflix.com",
    "alotporn.com",
    "vid2c.com",
    "Shufuni.com",
    "cliphunter.com",
    "xxxbunker.com",
    "madthumbs.com",
    "deviantclip.com",
    "twilightsex.com",
    "pornhost.com",
    "fux.com",
    "jizzhut.com",
    "spankbang.com",
    "eporner.com",
    "orgasm.com",
    "yuvutu.com",
    "kporno.com",
    "definebabe.com",
    "secret.shooshtime.com",
    "mofosex.com",
    "hotgoo.com",
    "submityourflicks.com",
    "xxx.com",
    "bigtits.com",
    "media.xxxaporn.com",
    "bonertube.com",
    "userporn.com",
    "jizzonline.com",
    "pornotube.com",
    "fookgle.com",
    "free18.net",
    "tub99.com",
    "nonktube.com",
    "mastishare.com",
    "tjoob.com",
    "rude.com",
    "bustnow.com",
    "pornrabbit.com",
    "pornative.com",
    "sluttyred.com",
    "boysfood.com",
    "moviefap.com",
    "lubetube.com",
    "submityourtapes.com",
    "megafilex.com",
    "hdpornstar.com",
    "al4a.com",
    "stileproject.com",
    "xogogo.com",
    "filthyrx.com",
    "jizzbo.com",
    "5ilthy.com",
    "91porn.com",
    "lesbianpornvideos.com",
    "eroxia.com",
    "iyottube.com",
    "yourfreeporn.us",
    "sexoasis.com",
    "fucktube.com",
    "pornomovies.com",
    "clearclips.com",
    "moviesand.com",
    "tubixe.com",
    "pornjog.com",
    "sextv1.pl",
    "desihoes.com",
    "pornupload.com",
    "kosimak.com",
    "videocasalinghi.com",
    "lubeyourtube.com",
    "freudbox.com",
    "moviesguy.com",
    "motherofporn.com",
    "141tube.com",
    "my18tube.com",
    "bigupload.comxvds.com",
    "fastjizz.com",
    "tubeland.com",
    "ultimatedesi.net",
    "teenporntube.com",
    "tubave.com",
    "afunnysite.com",
    "sexe911.com",
    "megaporn.com",
    "porntitan.com",
    "pornheed.com",
    "youhot.gr",
    "videolovesyou.com",
    "onlymovies.com",
    "hdporn.net",
    "adultvideodump.com",
    "suzisporn.com",
    "xfilmes.tv",
    "pornwall.com",
    "silverdaddiestube.com",
    "sextube.sweetcollegegirls.com",
    "ipadporn.com",
    "youporns.org",
    "movietitan.com",
    "yaptube.com",
    "jugy.com",
    "chumleaf.com",
    "panicporn.com",
    "milfporntube.com",
    "timtube.com",
    "wetpussy.com",
    "whoreslag.com",
    "xfapzap.com",
    "xvideohost.com",
    "tuberip.com",
    "dirtydirtyangels.com",
    "bigerotica.com",
    "pk5.net",
    "theamateurzone.info",
    "triniporn.org",
    "youbunny.com",
    "isharemybitch.com",
    "morningstarclub.com",
    "sexkate.com",
    "kuntfutube.com",
    "porncor.com",
    "thegootube.com",
    "tubeguild.com",
    "fuckuh.com",
    "tube.smoder.com",
    "zuzandra.com",
    "nextdoordolls.com",
    "myjizztube.com",
    "homesexdaily.com",
    "thetend.com",
    "yourpornjizz.com",
    "tgirls.com",
    "pornwaiter.com",
    "pornhub.pl",
    "nurglestube.com",
    "brazzershdtube.com",
    "upthevideo.com",
    "sexzworld.com",
    "cuntest.com",
    "ahtube.com",
    "free2peek.com",
    "freeamatube.com",
    "thexxxtube.net",
    "yazum.com",
    "tubesexes.com",
    "pornload.com",
    "vankoi.com",
    "dailee.com",
    "ejason21.com",
    "openpunani.com",
    "porntubexl.nl",
    "scafy.com",
    "bangbull.com",
    "vidxnet.com",
    "yteenporn.com",
    "tubethumbs.com",
    "faptv.com",
    "nasty8.com",
    "maxjizztube.com",
    "pornunder.com",
    "24h-porn.net",
    "xclip.tv",
    "jerkersworld.com",
    "desibomma.com",
    "jizzbox.com",
    "theyxxx.com",
    "bonkwire.com",
    "PornTelecast.com",
    "pornsitechoice.com",
    "yporn.tv",
    "girlsongirlstube.com",
    "famouspornstarstube.com",
    "sexfans.org",
    "youpornxl.com",
    "rudeshare.com",
    "efuckt.com",
    "koostube.com",
    "amateursex.com",
    "moviegator.com",
    "cobramovies.com",
    "cantoot.com",
    "yourhottube.com",
    "teentube18.com",
    "youxclip.com",
    "flicklife.com",
    "nastyrat.tv",
    "freepornfox.com",
    "freeadultwatch.com",
    "fucked.tv",
    "sextube.si",
    "pornrater.com",
    "wheresmygf.com",
    "xfanny.com",
    "pornorake.com",
    "untouched.tv",
    "guppyx.com",
    "mylivesex.tv",
    "pervaliscious.com",
    "sex2ube.com",
    "suckjerkcock.com",
    "netporn.nl",
    "exgfvid.com",
    "koalaporn.com",
    "bbhgvidz.com",
    "evilhub.com",
    "celebritytubester.com",
    "pornfish.com",
    "jrkn.com",
    "bootyclips.com",
    "tubeguide.info",
    "realhomemadetube.com",
    "tokenxxxporn.com",
    "pornvideoflix.com",
    "sinfultube.net",
    "pornler.com",
    "sharexvideo.com",
    "69youPorn.com",
    "submitmyvideo.com",
    "kastit.com",
    "pornini.com",
    "hd4sex.com",
    "laftube.com",
    "mosestube.com",
    "dutchxtube.com",
    "porncastle.net",
    "tubedatbooty.com",
    "pornvie.com",
    "pornopantry.com",
    "springbreaktubegirls.com",
    "tube4u.net",
    "nsfwftw.com",
    "pornozabava.com",
    "tgutube.com",
    "celebritynudez.com",
    "teeztube.com",
    "collegefucktube.com",
    "adultvideomate.com",
    "porntubemoviez.com",
    "bigjuggs.com",
    "hornypickle.com",
    "mypornow.com",
    "pushingpink.com",
    "xxxshare.ru",
    "nuuporn.com",
    "melontube.com",
    "myamateurporntube.com",
    "soyouthinkyourapornstar.com",
    "porntubestreet.com",
    "pornogoddess.com",
    "cumsnroses.com",
    "porntubeclipz.com",
    "lcgirls.com",
    "housewifes.com",
    "cactarse.com",
    "cumfox.com",
    "tube17.com",
    "teenbrosia.com",
    "lesbiantubemovies.com",
    "xxxset.com",
    "gagahub.com",
    "jugland.com",
    "porntubesurf.com",
    "freakybuddy.com",
    "sexdraw.com",
    "sexovirtual.com",
    "pornsmack.com",
    "gratisvideokijken.nl",
    "eroticadulttube.com",
    "bharatporn.com",
    "fmeporn.com",
    "darkpost.com",
    "sexporndump.com",
    "sexandporn.org",
    "jezzytube.com",
    "justpornclip.com",
    "xxxpornow.com",
    "inseks.com",
    "freeporn777.com",
    "porndisk.com",
    "adultfunnow.com",
    "youporn.us.com",
    "babecumtv.com",
    "girlskissinggirlsvideos.com",
    "specialtytubeporn.com",
    "teentube.be",
    "free-celebrity-tube.com",
    "public-sluts.net",
    "pornhub.org",
    "legioncaliente.com",
    "xpja.net",
    "oncam.me",
    "xpaja.net",
    "hentaix.to",
    "seebussy.com",
    "thebussybandit.com",
    "homo.xxx",
    "av01.tv",
    "jable.tv",
    "pandamovies.com",
    "tubegalore.com",
    "pichunter.com",
    "cherrypimps.com",
    "adultdvdempire.com",
    "ftopx.com",
    "hotmovies.com",
    "bluebirdfilms.com",
    "pornpics.com",
    "xfantazy.com",
    "adult.noodlemagazine.com"
]

const checkPage = () => {
    return new Promise((resolve, reject) => {

        // If URL contains whitelisted website - no blocking
        // If URL contains blocklisted or adult content website - block
        // If URL contains blocklisted or adult content keyword - block
        // Start checking DOM
        // If DOM contains 1 blocklisted keyword - block
        // If DOM contains 3 adult content keywords which are not whitelisted - block
        // GOOD WEBPAGE - no blocking

        try {
            const CURRENT_PAGE_URL_1 = decodeURIComponent(window.location.href)
            const CURRENT_PAGE_URL_2 = decodeURIComponent(window.location.href).toLowerCase().replace(/[`~!@#$%^&*()_|+\-=?;:'",.<>\{\}\[\]\\\/]/g, "")
            chrome.storage.local.get(['whiteList', 'blockList'])
                .then((info1) => {
                    const BLOCKLIST_WEBSITES = info1.blockList.websites
                    const BLOCKLIST_KEYWORDS = info1.blockList.keywords
                    const WHITELIST_WEBSITES = info1.whiteList.websites
                    const WHITELIST_KEYWORDS = info1.whiteList.keywords



                    console.log(info1?.blockList?.websites)
                    const WHITELIST_SWITCH_STATUS = true;

                    let checking_complete = false
                    let reason = ""

                    if (WHITELIST_SWITCH_STATUS) {
                        for (let i = 0; i < WHITELIST_WEBSITES.length; i++) {
                            const name = WHITELIST_WEBSITES[i]
                            if (CURRENT_PAGE_URL_1.includes(name)) {
                                checking_complete = true
                                break
                            }
                        }
                    }

                    if (checking_complete) {
                        resolve({
                            block: false
                        })
                    } else {
                        for (let i = 0; i < BLOCKLIST_WEBSITES.length; i++) {
                            const name = BLOCKLIST_WEBSITES[i]
                            if (CURRENT_PAGE_URL_1.includes(name)) {
                                checking_complete = true
                                reason = name
                                break
                            }
                        }
                        if (checking_complete) {
                            // block
                            resolve({
                                block: true,
                                url: CURRENT_PAGE_URL_1,
                                reason,
                                type: "blocklist",
                                category: "website"
                            })
                        } else {
                            for (let i = 0; i < ADULT_WEBSITE_LIST.length; i++) {
                                const name = ADULT_WEBSITE_LIST[i]
                                if (CURRENT_PAGE_URL_1.includes(name)) {
                                    checking_complete = true
                                    reason = name
                                    break
                                }
                            }

                            if (checking_complete) {
                                // block
                                resolve({
                                    block: true,
                                    url: CURRENT_PAGE_URL_1,
                                    reason,
                                    type: "adultlist",
                                    category: "website"
                                })
                            } else {
                                if (CURRENT_PAGE_URL_2.includes('funswitch') || CURRENT_PAGE_URL_2.includes('blockerx') || CURRENT_PAGE_URL_2.includes('atmana')) {
                                    resolve({
                                        block: false
                                    })
                                } else {
                                    for (let i = 0; i < BLOCKLIST_KEYWORDS.length; i++) {
                                        const name = Object.values(BLOCKLIST_KEYWORDS[i])[0].split(" ").join("")
                                        if (CURRENT_PAGE_URL_2.includes(name) || CURRENT_PAGE_URL_2.includes(name.toLowerCase())) {
                                            checking_complete = true
                                            reason = name
                                            break
                                        }
                                    }
                                    if (checking_complete) {
                                        // block
                                        resolve({
                                            block: true,
                                            url: CURRENT_PAGE_URL_1,
                                            reason,
                                            type: "blocklist",
                                            category: "keyword"
                                        })
                                    } else {
                                        for (let i = 0; i < ADULT_KEYWORD_LIST.length; i++) {
                                            const name = ADULT_KEYWORD_LIST[i]
                                            if (CURRENT_PAGE_URL_2.includes(name)) {
                                                checking_complete = true
                                                reason = name
                                                break
                                            }
                                        }

                                        if (checking_complete) {
                                            //block
                                            resolve({
                                                block: true,
                                                url: CURRENT_PAGE_URL_1,
                                                reason,
                                                type: "adultlist",
                                                category: "keyword"
                                            })
                                        } else {
                                            // CHECK DOM
                                            document.addEventListener("DOMContentLoaded", () => {
                                                let CURRENT_PAGE_DOM = document.documentElement.innerHTML.toLowerCase().replace(/[`~ !@#$%^&*()_|+\-=?;:'",.<>\{\}\[\]\\\/]/g, "");

                                                if (CURRENT_PAGE_DOM.includes('funswitch') || CURRENT_PAGE_DOM.includes('blockerx') || CURRENT_PAGE_DOM.includes('atmana')) {
                                                    // no blocking
                                                    resolve({
                                                        block: false
                                                    })
                                                } else {
                                                    for (let i = 0; i < BLOCKLIST_KEYWORDS.length; i++) {
                                                        const name = Object.values(BLOCKLIST_KEYWORDS[i])[0]
                                                        if (CURRENT_PAGE_DOM.includes(name)) {
                                                            checking_complete = true
                                                            reason = name
                                                            break
                                                        }
                                                    }
                                                    if (checking_complete) {
                                                        // block
                                                        resolve({
                                                            block: true,
                                                            url: CURRENT_PAGE_URL_1,
                                                            reason,
                                                            type: "blocklist",
                                                            category: "keyword"
                                                        })
                                                    } else {
                                                        let count_of_adult_keywords = 0
                                                        let temp_whitelist_keywords = []
                                                        for (let i = 0; i < WHITELIST_KEYWORDS.length; i++) {
                                                            const name = Object.values(WHITELIST_KEYWORDS[i])[0]
                                                            temp_whitelist_keywords.push(name)
                                                        }
                                                        for (let i = 0; i < ADULT_KEYWORD_LIST; i++) {
                                                            const name = ADULT_KEYWORD_LIST[i]
                                                            if (!temp_whitelist_keywords.includes(name) && CURRENT_PAGE_DOM.includes(name)) {
                                                                count_of_adult_keywords = count_of_adult_keywords + 1
                                                                if (count_of_adult_keywords === 3) {
                                                                    reason = name
                                                                    checking_complete = true
                                                                    break
                                                                }
                                                            }
                                                        }
                                                        if (checking_complete) {
                                                            // block
                                                            resolve({
                                                                block: true,
                                                                url: CURRENT_PAGE_URL_1,
                                                                reason,
                                                                type: "adultlist",
                                                                category: "keyword"
                                                            })
                                                        } else {
                                                            // no blocking
                                                            resolve({
                                                                block: false
                                                            })
                                                        }
                                                    }
                                                }
                                            })
                                        }
                                    }
                                }
                            }
                        }
                    }
                })
                .catch((err1) => {
                    resolve({
                        block: false
                    })
                })
        } catch (e) {
            resolve({
                block: false
            })
        }
    })
}

const checkForBlocking = async () => {
    const result = await checkPage();

    if (result.block) {
        const appId = chrome.runtime.id
        window.open(`chrome-extension://${appId}/blocked.html?url=${result.url}`, "_self")
    }
}

const checkSearch = () => {
    try {
        const websiteURL = window.location.href
        if (websiteURL.indexOf('google.') !== -1) {
            if (websiteURL.indexOf('&safe=strict') === -1 && /q=/.test(websiteURL)) {
                window.location.replace(websiteURL + '&safe=strict')
            } else {
                checkForBlocking()
            }
        } else if (websiteURL.indexOf('search.yahoo.') !== -1) {
            if (websiteURL.indexOf('&vm=r') === -1 && /(\/search)/.test(websiteURL)) {
                window.location.replace(websiteURL + '&vm=r')
            } else {
                checkForBlocking()
            }
        } else if (websiteURL.indexOf('bing.') !== -1) {
            if (websiteURL.indexOf('&adlt=strict') === -1 && /(\/search|\/videos|\/images|\/news)/.test(websiteURL)) {
                window.location.replace(websiteURL + '&adlt=strict')
            } else {
                checkForBlocking()
            }
        } else if (websiteURL.indexOf('duckduckgo.') !== -1) {
            if (websiteURL.indexOf('&kp=1') === -1 && websiteURL.indexOf('q=') !== -1) {
                window.location.replace(websiteURL + '&kp=1')
            } else {
                checkForBlocking()
            }
        } else if (websiteURL.indexOf('facebook.') !== -1) {
            if (websiteURL.indexOf('&safe=strict') === -1 && websiteURL.indexOf('q=') !== -1) {
                window.location.replace(websiteURL + '&safe=strict')
            } else {
                checkForBlocking()
            }
        } else {
            checkForBlocking()
        }
    } catch {
        checkForBlocking()
    }
};

checkSearch();